### ISSUE TITLE
some darwin binaries missing python

### ISSUE THREAD

**Issue by scottyhq** [geodynamics/pylith#29]
I noticed the most recent darwin binaries are missing the 'include' folder and links to python2.7 in the bin/ folder. This causes pylith to use whatever python version is the in the user's path and can lead to errors such as this one:

Exception: Unable to import the Python Scientific module required by FIAT.
Consider installing the package python-scientific.

This seems to be the case for versions > 2.1.2
pylith-2.1.1-darwin-10.6.8:
bin      etc      include  lib      setup.sh share    src

pylith-2.1.2-darwin-10.10.5:
bin      lib      setup.sh share    src

pylith-2.1.3-darwin-10.10.5:
bin      lib      setup.sh share    src

pylith-2.1.4-darwin-10.11.6:
bin      lib      setup.sh share    src

**Comment by baagaard-usgs** [comment]
These latest Darwin binaries are built against the system Python so they do not include Python.

With PyLith as with all software It is important for users to setup their environment so that they prevent conflicts among the suite of software that they have installed. I will add a warning in the manual about potential conflicts with other software installed and how to setup the environment accordingly.

**Comment by baagaard-usgs** [comment]
I have adjusted the packaging so that the v2.2.0 binary to include all files necessary to use the binary packages for extending PyLith and/or building other software for integration with PyLith. For Darwin we use the clang compiler and Python provided by the system, so they are not bundled. For Linux, the packager now includes the GNU gcc compiler suite.

The v2.2.0 user manual also include appropriate warnings and notes in the installation chapter regarding these issues.
