### ISSUE TITLE
Bug in root finding for PowerLaw bulk rheology

### ISSUE THREAD

**Issue by baagaard-usgs** [geodynamics/pylith#450]
## Describe the bug

Root finding for PowerLaw bulk rheology fails at first time step for `examples/reverse-2d/step08_twofaults_powerlaw.cfg`.
`_effStressFuncDerivFunc()` returns `funcValue=2.7308271076170137E+135` and `funcDeriv=2.6549707990720962E+137`. 

## To Reproduce

**PETSc branch**: `knepley/pylith`
**PyLith branch**: `main`

Build and install

```
cd examples/reverse-2d
pylith step08_twofaults_powerlaw.cfg
```

### Error message

```
 -- Solving problem.
0 TS dt 0.2 time -0.2
    0 SNES Function norm 2.225574998436e-02 
    Linear solve converged due to CONVERGED_ATOL iterations 903
libc++abi: terminating with uncaught exception of type std::runtime_error: Cannot find root of effective stress function.
[0]0:Return code = 0, signaled with Abort trap: 6
```

### Comments

I have no idea where the error is. It could be in the simulation setup (power-law parameters), nondimensionalization of the power-law parameters, or in the power-law rheology functions. The same simulation with a linear Maxwell model appears to work as expected.

**Comment by willic3** [comment]
There were a few issues. The power-law reference strain and stress were reversed in the spatialdb file, which caused the main problem. Once I fixed that, the effective viscosity was much too high (essentially elastic). I modified the parameters to give some viscous relaxation (while still converging), but the problem is still not very interesting for power-law. There is a huge range of relaxation times (ranging from 0.06 to several hundred thousand in terms of the normalization parameter). I suspect that we would need a much more graded mesh and possibly a longer time period to adequately model this problem.
