### ISSUE TITLE
Use label name and value for output from physics objects

### ISSUE THREAD

**Issue by baagaard-usgs** [geodynamics/pylith#501]
## Describe the bug

We ignore the label name and value when outputting solution subfields and derived subfields from physics objects. We can get away with this for materials and boundary conditions, but it won't work for faults because we need the DS for the fault fields.

## Proposed fix

Get the label name and value from the physics object when we project the field.

**Comment by baagaard-usgs** [comment]
@knepley I have an initial implementation. Projecting with the label seems to work for boundaries but not for materials. For the materials, I see the values being set in my passThruSubfield kernel but the vector after the projection is all zeros.

## Reproduce

* **PETSc branch**: `knepley/pylith`
* **PyLith branch**: `baagaard/fix-output-physics`

```
# build
make check -C tests/fullscale/cornercases/nofaults-2d
```

**Comment by knepley** [comment]
I know what the problem is. Plex is very specific about interpolation. If the point on which the dual basis vector sits in not labeled, you do not get any values. For example, if unknowns are at vertices (P1) but only cells are labeled, then you get no values. In this example, the material-id label only has cells, but the unknowns are on vertices. You can fix this by calling `DMPlexLabelComplete()` on the label.

@baagaard-usgs I am not sure how you want to handle this. I think I would create a copy of the input label and complete it. What do you think?
