### ISSUE TITLE
Installation help

### ISSUE THREAD

**Issue by vikasrajisro** [geodynamics/pylith#664]
To install pylith on my ubuntu machine i followed by Command as given in manual
1.  ./configure
2.  source setup.sh
3. make
 first two commands performing well but i am facing a  error in make command 

**./libtool: line 7471: cd: NONE/lib: No such file or directory
libtool:   error: cannot determine absolute directory name of 'NONE/lib'
make[3]: *** [Makefile:453: libsqlite3.la] Error 1
make[3]: Leaving directory '/home/vikas/src/pylith/pylith-installer-3.0.3-0/dependencies/sqlite-build'
make[2]: *** [Makefile:1102: sqlite] Error 2
make[2]: Leaving directory '/home/vikas/src/pylith/pylith-installer-3.0.3-0/dependencies'
make[1]: *** [Makefile:1114: installed_sqlite] Error 2
make[1]: Leaving directory '/home/vikas/src/pylith/pylith-installer-3.0.3-0/dependencies'
make: *** [Makefile:566: all-recursive] Error 1**

it will be great if someone suggest to how to tackle the issue
Thanks for considering the issue.

**Comment by baagaard-usgs** [comment]
Is there a reason you are trying to build PyLith from source rather than using the Linux binary package? In general, you should only have to build from source if you want to modify or extend the code or are running it on a cluster. The Linux binary package should work on Ubuntu 18.04 or later.

If you must build from source, then please provide the `config.log` that was generated when you ran configure. What version of Ubuntu are you using?

**Comment by vikasrajisro** [comment]
Thanks Mr. bagaard-usgs i go through the binary packages and now its working smoothly.
