### ISSUE TITLE
 is it possible to install the Pylith in conda enviroment? how?

### ISSUE THREAD

**Issue by GEOSCIENCELXG** [geodynamics/pylith#776]
## Describe the issue

**As a Pylith begainer who wants to avoid potential conflicts of dependencies, Can we install Pylith in one conda environment? and how?**

**Comment by baagaard-usgs** [comment]
We recommend using the PyLith binary package. It uses its own Python virtual environment. The `setup.sh` script supplied with the binary package will adjust the `PATH` and `PYTHONPATH` environment variables to point to the Python virtual environment for PyLith. We have found that this works in most cases; the biggest exception is usually people who have Python from conda in their `PATH`. In general, we recommend having a minimal environment (for example, `PYTHONPATH` not set and `PATH` pointing to just `/bin:/usr/bin:/sbin:/usr/sbin`) when you run `source setup.sh` for the PyLith binary. 

We have not created a PyLith conda setup, because PyLith depends on several C or C++ packages that are not available in conda, and we do not have the resources to setup and maintain conda builds for the dependencies. If you must build from source (for example, on a cluster), then we recommend using the [PyLith installer](https://pylith-installer.readthedocs.io/en/latest/) to build PyLith and whatevever dependencies you need to build.

**Comment by GEOSCIENCELXG** [comment]
Thanks @baagaard-usgs
